trigger:
- main

variables:
  vmImageName: 'myPackerImage'
  webAppName: 'myApplication-AppService'
  python.version: '3.7.6'
  azureServiceConnectionId: 'myserviceconnection'
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'Test'

stages:
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    # ... (other tasks)

- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-18.04'
    environment: Test
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'a3a536c2-3690-4c5f-8032-998a8dc3234e'
              appName: 'mywebapp'
              appType: webApp
              package: $(Pipeline.Workspace)/<artifact>/<archiveFile>

    # ... (other tasks)
