trigger:
- main

variables:
  vmImageName: 'myimage_gallery'
  webAppName: 'myApplication1-AppService' #'mywebappBBfinal'
  python.version: '3.7.6'
  azureServiceConnectionId: 'myserviceconnection'
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'Test'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 
      VMimage: ubuntu-20.04
      
    steps:
    #- task: Bash@3
    #  displayName: 'Install Postman & Newman'
    #  inputs:
     #  targetType: 'inline'
     #  script: |
     #     #! /bin/bash
     #     pwd
  #--------------------------------------------#  
    # Use Terraform to create the Infrastructure      
    # Install Terraform on the pipeline agent 
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Terrafom installation'
      inputs:
        terraformVersion: '1.2.9'


    # Run Terraform Init on the pipeline agent 
    # ToDo: Replace the resource group name, storage account name, and container name below
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: 'Terrafom init'
      inputs:
         Arguments: 
         InstallTerraform: true
         UseAzureSub: true
         ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
         ConnectedServiceNameARM: 'ConnectedServiceNameARM'
         ManageState: false

         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
         backendServiceArm: 'myserviceconnection'
         backendAzureRmResourceGroupName: 'tfstatebb8'
         backendAzureRmStorageAccountName: 'tfstatebb8'
         backendAzureRmContainerName: 'tfstatebb8'
         backendAzureRmKey: 'test.terraform.tfstate'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: 'myserviceconnection'

    
    # Run Terraform Apply
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        #commandOptions: '-var "public_key_path=$(public_key.secureFilePath)"'
        environmentServiceNameAzureRM: 'myserviceconnection'

    #- task: Bash@3
    #  displayName: 'Install Postman & Newman'
    #  inputs:
     #  targetType: 'inline'
     #  script: |
     #     #! /bin/bash
     #     pwd

    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    #- task: CmdLine@2
    #  displayName: Run Regression Tests
   #   continueOnError: true
    #  inputs:
    #    script: 'newman run StarterAPIs.json'
     #   workingDirectory: 'starter-code/automatedtesting/postman'         

              
    # ToDo: Change the workingDirectory path, as applicable to you
    # Destroy the resources in Azure by running a separate pipeline. 
    
    #- task: ArchiveFiles@2
    #  displayName: 'Archive FakeRestAPI'
    #  inputs:
     #   rootFolderOrFile: 'automatedtesting/jmeter/fakerestapi'
    #    includeRootFolder: false
     #   archiveType: 'zip'
     #   archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    #- publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    #  displayName: 'Upload fakerrestapi Package'
    #  artifact: drop-fakerestapi
    - task: ArchiveFiles@2
      displayName: 'Archive Fakerestapi'
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)/$(Build.BuildID)-fakerestapi.zip'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)/$(Build.BuildID)-automatedtests.zip'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-automatedtests.zip'
        replaceExistingArchive: false

- stage: WebAppDeployment
  displayName: Web App Deployment
  jobs:
  - deployment: FakeRestAPI
    environment:
          name: 'Test'
          #resourceType: VirtualMachine
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'myserviceconnection'
              appType: 'webAppLinux'
              appName: 'mywebappBBfinal-AppService'
              package: '$(System.DefaultWorkingDirectory)/**/fakerestapi.zip'
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'myserviceconnection'
              appName: 'mywebappBBfinal-AppService' #'mywebappBBfinal'
              appType: 'webAppLinux'
              package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                 echo 'FakeRestAPI Running'
  #- deployment: VMDeploy
  #  displayName: Deploy VM
   # environment:
   #   name: 'Test VM'
   #   resourceType: VirtualMachine
    #strategy:
    # runOnce:
    #   deploy:
     #   steps:
          
               
  
    #--------------------------------------------#    
          # Run JMeter test suite against the App Service
       #   - task: Bash@3
    #  displayName: 'Install Postman & Newman'
    #  inputs:
     #  targetType: 'inline'
     #  script: |
     #     #! /bin/bash
     #     pwd

    
- stage: Jmeter
  displayName: JMeter Test
  jobs:
  - job: JMeterTest
    displayName: JMeterTests
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          wget "https://apache.mirrors.lucidnetworks.net//jmeter/binaries/apache-jmeter-5.2.1.tgz"
          tar -xf apache-jmeter-5.2.1.tgz
          unzip -o $(Build.BuildId)-perftests.zip
          ./apache-jmeter-5.2.1/bin/jmeter -n -t PerformanceTestSuite.jmx -j jmeter.log -f
          cat jmeter.log                                                                           # ToDo: Write your commands
          workingDirectory: '$(System.DefaultWorkingDirectory)'#(Pipeline.Workspace)/<artifact>            # ToDo: Use the artifact name from the task above
              
    #--------------------------------------------#  
    # Selenium | Functional UI Tests
    # ToDo: 
  - deployment: VMDeploy
    displayName: Selenium Tests
    environment:
      name:        'Test'
      resourceType: VirtualMachine
    pool:
      vmImage: 'myimage_gallery'
     # tags: selenium
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop-ui-tests     # ToDo: Change/provide a name
            
- stage: Postman
  displayName: Postman Test
  jobs:
  - job: PostmanTest
    displayName: PostmanTests
    steps:
      - task: Bash@3
        displayName: 'Run Postman/Newman Tests'
        inputs:
          targetType: 'inline'
          script: |
            sudo npm install -g newman reporter
            echo 'Starting Tests...'
            echo 'Running Regression Test'
            newman run automatedtesting/postman/RegressionTest.postman_collection.json  --delay-request 12000 --reporters cli,junit --suppress-exit-code
            echo 'Running Data Validation Test'
            # newman run automatedtesting/postman/ValidationTest.postman_collection.json  --delay-request 12000 --reporters cli,junit --suppress-exit-code
      - task: PublishTestResults@2
        displayName: 'Publish Postman Newman Results **/newman-*.xml'
        condition: always()
        inputs:
            testResultsFormat: 'JUnit'
            testRunTitle: Data and Regression Tests
            testResultsFiles: '**/newman-*.xml'     
#- stage: final
 # jobs:
 # - job: Destroy
 #   displayName: Terraform Destroy
 #   pool:
 #     vmImage: 'myimage_gallery'
 #   steps:
  #  - task: TerraformCLI@0
   # inputs:
   #  command: 'destroy'
   #  environmentServiceName: 'project(2d04f73e-87e7-4ffd-aa6f-c28d4b64c42b)'
    # allowTelemetryCollection: true
    #inputs:
    #  command: 'destroy'
     # workingDirectory: $(System.DefaultWorkingDirectory)/terraform/environments
    #  environmentServiceName: 'myserviceconnection'
      #secureVarsFile: 'terraform.tfvars'

